# Generated by Django 5.0 on 2025-09-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PLACED', 'PLACED'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=12),
        ),
    ]
